apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: shared-storage # Deve essere uguale a quella del PV
  resources:
    requests:
      storage: 5Gi
