apiVersion: v2
name: postgresql
description: Wrapper per PostgreSQL Multi-DB
version: 1.0.0
appVersion: "16.0"

dependencies:
  - name: postgresql
    version: "18.2.4"
    repository: "oci://registry-1.docker.io/bitnamicharts"
